# -*- coding: utf-8 -*-
"""email classifier app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1StD8XQ5SyKB9wmfNmruB_BHQbuFYOt3M
"""

import streamlit as st
import joblib

# Load model
model = joblib.load('spam_classifier.pkl')

# Title
st.title("Email Spam Classifier")

# Input
email = st.text_area("Paste your email content here")

# Predict
if st.button("Check"):
    prediction = model.predict([email])[0]
    result = "Spam 🚫" if prediction == 1 else "Not Spam ✅"
    st.success(f"Result: {result}")