# -*- coding: utf-8 -*-
"""email classifier app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1StD8XQ5SyKB9wmfNmruB_BHQbuFYOt3M
"""

import streamlit as st
import pickle
import joblib
joblib.dump(model, "spam_classifier.pkl")
# Then in Streamlit
model = joblib.load("spam_classifier.pkl")
st.title("📧 Spam Classifier")
st.write("Enter an email and let the model decide: Spam or Not Spam")

# Text input
email_input = st.text_area("Enter your email content here")


# Predict button
if st.button("Classify"):
    prediction = model.predict([email_input])
    if prediction[0] == 1:
        st.error("🚨 This looks like spam!")
    else:
        st.success("✅ This seems clean.")