# -*- coding: utf-8 -*-
"""trained model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eYo7Ng6biCnhkopS_O9gfGO_AJRU75EL
"""

import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
import joblib

# Load your dataset
data = pd.read_csv('spam.csv', encoding='latin-1')  # Adjust encoding if needed
data = data[['v1', 'v2']]  # Rename if necessary
data.columns = ['label', 'text']

# Convert labels to binary
data['label'] = data['label'].map({'ham': 0, 'spam': 1})

# Define pipeline with smarter text weighting
pipeline = Pipeline([
    ('vectorizer', TfidfVectorizer()),
    ('classifier', MultinomialNB())
])

# Train and save
pipeline.fit(data['text'], data['label'])
joblib.dump(pipeline, 'spam_classifier.pkl')