# -*- coding: utf-8 -*-
"""trained model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eYo7Ng6biCnhkopS_O9gfGO_AJRU75EL
"""

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
import joblib

# Sample training data
data = pd.DataFrame({
    'text': ['Free money now!', 'Hi, how are you?', 'Win a prize', 'Meeting at noon'],
    'label': [1, 0, 1, 0]  # 1 = spam, 0 = not spam
})

# Define pipeline
pipeline = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('classifier', MultinomialNB())
])

# Train and save
pipeline.fit(data['text'], data['label'])
joblib.dump(pipeline, 'spam_classifier.pkl')