# -*- coding: utf-8 -*-
"""trained model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eYo7Ng6biCnhkopS_O9gfGO_AJRU75EL
"""

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
import joblib

# Sample training data
df = pd.read_csv('/content/Spam.csv', encoding='latin-1')[['v1', 'v2']]
df.columns = ['label', 'text']
# Optional: Clean your text
def clean_text(text):
    import re
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"\W+", " ", text)
    return text

data['text'] = data['text'].apply(clean_text)


# Define pipeline
pipeline = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('classifier', MultinomialNB())
])

# Train and save
pipeline.fit(data['text'], data['label'])
joblib.dump(pipeline, 'spam_classifier.pkl')